### ISSUE TITLE
 issue with plant-image-classification Dataset 

### ISSUE THREAD

**Issue by Abhinav-Amarapuram** [clarkjanndy/plant-image-classification#1]
No file or directory found at /content/gdrive/My Drive/Medplants Resources/CNN-MedNet.h5
 Could you please help me in finding this.  Thank you .

**Comment by clarkjanndy** [comment]
You need to save the model first (run the 14th codeblock), download the model and then upload it to your google drive. Make sure also to change `model_dir ` with the path where you uploaded the model.
